/** Municipios / ciudades principales de Colombia (orden alfabético, escritura unificada). */
export const CIUDADES_COLOMBIA: readonly string[] = [
  "Aguachica",
  "Apartadó",
  "Arauca",
  "Armenia",
  "Barrancabermeja",
  "Barranquilla",
  "Bello",
  "Bogotá D.C.",
  "Bucaramanga",
  "Buenaventura",
  "Buga",
  "Cali",
  "Cartagena",
  "Cartago",
  "Caucasia",
  "Cereté",
  "Chía",
  "Chinchiná",
  "Chiquinquirá",
  "Ciénaga",
  "Cúcuta",
  "Dosquebradas",
  "Duitama",
  "Envigado",
  "Facatativá",
  "Florencia",
  "Floridablanca",
  "Fundación",
  "Girardot",
  "Girón",
  "Ibagué",
  "Ipiales",
  "Itagüí",
  "Jamundí",
  "La Dorada",
  "La Estrella",
  "Lorica",
  "Los Patios",
  "Magangué",
  "Maicao",
  "Malambo",
  "Manizales",
  "Medellín",
  "Mocoa",
  "Montería",
  "Neiva",
  "Ocaña",
  "Palmira",
  "Pasto",
  "Pereira",
  "Piedecuesta",
  "Pitalito",
  "Popayán",
  "Puerto Asís",
  "Puerto Berrío",
  "Puerto Carreño",
  "Quibdó",
  "Riohacha",
  "Rionegro",
  "Sabaneta",
  "Sahagún",
  "San Andrés",
  "San Gil",
  "Santa Marta",
  "Santander de Quilichao",
  "Sincelejo",
  "Soacha",
  "Sogamoso",
  "Soledad",
  "Tibú",
  "Tuluá",
  "Tunja",
  "Turbo",
  "Valledupar",
  "Villavicencio",
  "Yopal",
  "Yumbo",
  "Zipaquirá",
] as const;

const SET_CIUDADES = new Set<string>(CIUDADES_COLOMBIA);

/** Si el valor guardado no está en la lista, se muestra como opción extra en el select. */
export function opcionesCiudadColombia(valorActual: string): string[] {
  const v = valorActual.trim();
  if (!v || SET_CIUDADES.has(v)) return [...CIUDADES_COLOMBIA];
  return [...CIUDADES_COLOMBIA, v];
}
